version: '3'
services:
  php:
    build:
      context: ./php
    working_dir: /app
    volumes:
      - ../:/app:cached
    command: composer update
    stdin_open: true
  php_cli:
    build:
      context: ./php
    working_dir: /app
    volumes:
      - ../:/app:cached
    stdin_open: true